apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: aha-ai-demo
  labels:
    app: aha-ai-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aha-ai-demo
  template:
    metadata:
      annotations:
        timestamp: {{ now | quote }}
      labels:
        app: aha-ai-demo
    spec:
      containers:
        - name: aha-ai-demo
          image: registry.digitalocean.com/scytale/aha-ai-demo:latest
          imagePullPolicy: Always
          ports:
            - name: liveness-port
              containerPort: 3000
          command:
            - "pnpm"
            - "start"
#          livenessProbe:
#            httpGet:
#              path: /
#              port: liveness-port
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            timeoutSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /
#              port: liveness-port
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: aha-ai-demo
spec:
  selector:
    app: aha-ai-demo
  ports:
    - port: 3000
      targetPort: 3000
