apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: api-service
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      annotations:
        timestamp: {{ now | quote }}
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: {{ .Values.repository }}/api-service:{{ .Values.tag}}
          imagePullPolicy: Always
          ports:
            - name: liveness-port
              containerPort: 3020
          command:
            - "npm"
            - "run"
            - "start:{{ .Values.env }}"
          env:
            - name: env
              value: {{ .Values.env | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: liveness-port
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: liveness-port
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: api-service
spec:
  selector:
    app: api-service
  ports:
    - port: 3020
      targetPort: 3020
