name: api-service-ci

on:
  push:
    branches: [development]
  pull_request: 
    branches: [main]

jobs:
  Push-Repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Log into Digial Ocean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Build, tag, and push image to Digital Ocean Registry
        env:
          REGISTRY: registry.digitalocean.com/scytale
          REPOSITORY : api-service
          IMAGE_TAG : ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f ./services/$REPOSITORY/Dockerfile .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
          docker push $REGISTRY/$REPOSITORY:latest